# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Setup term for programs to be able to use it
env:
  # TERM: alacritty
  TERM: xterm-256color

window:
  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true
  opacity: 0.9 
  # Startup Mode (changes require restart)
  startup_mode: Fullscreen

# Sample Font configuration for font: Monoid.
# Feel free to use different font configuration family & face for each sections
font:
  # Normal font face - Also used to draw glyphs on tmux & VIM
  # NOTE: You may use any font you'd like but make sure the normal fonts
  # support ligatures/glyphs. That's used by tmux & VIM to provide a better
  # UI for powerline & tmux bottom bar.
  normal:
    # Font name
    family: FiraCode Nerd Font
    # Font face
    style: Regular

  # Bold font face
  bold:
    family: FiraCode Nerd Font
    style: Bold 

  # Italic font face
  italic:
    family: FiraCode Nerd Font
    style: Italic

  # Bold italic font face
  # Note: Since i don't have a font italic version of this font, I just specified
  # italic & it just works. You may specifiy the bold italic version if it exists
  # for your font
  bold_italic:
    family: FiraCode Nerd Font
    style: Italic

  # Font size
  size: 17.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing
  # I've given in 14 spacing which fits really well with my fonts, you may change it
  # to your convenience but make sure to adjust 'glyph_offset' appropriately post that
  # offset:
  #  x: 0
  #  y: 14

  # Note: This requires RESTART
  # By default when you change the offset above you'll see an issue, where the texts are bottom
  # aligned with the cursor, this is to make sure they center align.
  # This offset should usually be 1/2 of the above offset-y being set.
  # glyph_offset:
  #  x: 0
  #  # Keeping this as half of offset to vertically align the text in cursor
   # y: 7

  # Better font rendering for mac
  use_thin_strokes: true

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true


# Live config reload (changes require restart)
live_config_reload: true

# Setup some amazing custom key bindings here - Best thing is you can setup key bindings
# using Mac's 'command' to control your tmux.
# A great reference: https://arslan.io/2018/02/05/gpu-accelerated-terminal-alacritty/#make-alacritty-feel-like-iterm2
key_bindings:
  - { key: D,     mods: Command,       chars: "\x06\x76" } 
  - { key: D,     mods: Command|Shift, chars: "\x06\x73" }
  - { key: W,     mods: Command,       chars: "\x06\x78" }
  - { key: H,     mods: Command,       chars: "\x06\x68" }
  - { key: J,     mods: Command,       chars: "\x06\x6a" }
  - { key: K,     mods: Command,       chars: "\x06\x6b" }
  - { key: L,     mods: Command,       chars: "\x06\x6c" }
  - { key: T,     mods: Command,       chars: "\x06\x63" }
  - { key: Key1,  mods: Command,       chars: "\x06\x31" }
  - { key: Key2,  mods: Command,       chars: "\x06\x32" }
  - { key: Key3,  mods: Command,       chars: "\x06\x33" }
  - { key: Key4,  mods: Command,       chars: "\x06\x34" }
  - { key: Key5,  mods: Command,       chars: "\x06\x35" }
  - { key: Key6,  mods: Command,       chars: "\x06\x36" }
  - { key: Key7,  mods: Command,       chars: "\x06\x37" }
  - { key: Key8,  mods: Command,       chars: "\x06\x38" }
  - { key: Key9,  mods: Command,       chars: "\x06\x39" }
  - { key: Left,  mods: Command,       chars: "\x06\x48" }
  - { key: Down,  mods: Command,       chars: "\x06\x4a" }
  - { key: Up,    mods: Command,       chars: "\x06\x4b" }
  - { key: Right, mods: Command,       chars: "\x06\x4c" }


# Colors (Gruvbox dark)
# colors:
#   # Default colors
#   primary:
#     # hard contrast: background = '#1d2021'
#     background: '#282828'
#     # soft contrast: background = '#32302f'
#     foreground: '#ebdbb2'

#   # Normal colors
#   normal:
#     black:   '#282828'
#     red:     '#cc241d'
#     green:   '#98971a'
#     yellow:  '#d79921'
#     blue:    '#458588'
#     magenta: '#b16286'
#     cyan:    '#689d6a'
#     white:   '#a89984'

#   # Bright colors
#   bright:
#     black:   '#928374'
#     red:     '#fb4934'
#     green:   '#b8bb26'
#     yellow:  '#fabd2f'
#     blue:    '#83a598'
#     magenta: '#d3869b'
#     cyan:    '#8ec07c'
#     white:   '#ebdbb2'

colors:
  # Default colors
  primary:
    background: '0x282a36'
    foreground: '0xf8f8f2'

    # Bright and dim foreground colors
    #
    # The dimmed foreground color is calculated automatically if it is not present.
    # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
    # is `false`, the normal foreground color will be used.
    #dim_foreground: '0x9a9a9a'
    #bright_foreground: '0xffffff'

  # Cursor colors
  #
  # Colors which should be used to draw the terminal cursor. If these are unset,
  # the cursor color will be the inverse of the cell color.
  cursor:
    text: '0x44475a'
    cursor: '0xf8f8f2'

  # Selection colors
  #
  # Colors which should be used to draw the selection area. If selection
  # background is unset, selection color will be the inverse of the cell colors.
  # If only text is unset the cell text color will remain the same.
  selection:
    text: '0xf8f8f2'
    background: '0x44475a'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xff5555'
    green:   '0x50fa7b'
    yellow:  '0xf1fa8c'
    blue:    '0xbd93f9'
    magenta: '0xff79c6'
    cyan:    '0x8be9fd'
    white:   '0xbfbfbf'

  # Bright colors
  bright:
    black:   '0x4d4d4d'
    red:     '0xff6e67'
    green:   '0x5af78e'
    yellow:  '0xf4f99d'
    blue:    '0xcaa9fa'
    magenta: '0xff92d0'
    cyan:    '0x9aedfe'
    white:   '0xe6e6e6'

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  dim:
    black:   '0x14151b'
    red:     '0xff2222'
    green:   '0x1ef956'
    yellow:  '0xebf85b'
    blue:    '0x4d5b86'
    magenta: '0xff46b0'
    cyan:    '0x59dffc'
    white:   '0xe6e6d1'

  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #
  # Example:
  #   `- { index: 16, color: '0xff00ff' }`
  #
  indexed_colors: []

# monokia
# colors:
#   # Default colors
#   primary:
#     background: '0x272822'
#     foreground: '0xf8f8f2'

#   # Colors the cursor will use if `custom_cursor_colors` is true
#   cursor:
#     text: '0x272822'
#     cursor: '0xf8f8f2'

#   # Normal colors
#   normal:
#     black:   '0x272822'
#     red:     '0xf92672'
#     green:   '0xa6e22e'
#     yellow:  '0xf4bf75'
#     blue:    '0x66d9ef'
#     magenta: '0xae81ff'
#     cyan:    '0xa1efe4'
#     white:   '0xf8f8f2'

#   # Bright colors
#   bright:
#     black:   '0x75715e'
#     red:     '0xfd971f'
#     green:   '0x383830'
#     yellow:  '0x49483e'
#     blue:    '0xa59f85'
#     magenta: '0xf5f4f1'
#     cyan:    '0xcc6633'
#     white:   '0xf9f8f5'

# draw_bold_text_with_bright_colors: false
