require("system.setup").setup {
  transparent_window = false,
  format_on_save = true,
  better_fold = true,
  better_tui = false,
  -- colorscheme = "duskfox",
  -- colorscheme = "nightfly",
  -- colorscheme = "nightfox",
  -- colorscheme = "github_dimmed",
  -- colorscheme = "tokyonight",
  -- colorscheme = "sonokai",
  -- colorscheme = "onedarkpro",
  -- colorscheme = "monokai_soda",
  colorscheme = "catppuccin",
  -- colorscheme = "rose-pine",
  -- colorscheme = "tokyonight",
  -- colorscheme = "tokyodark",
  -- colorscheme = "kanagawa",
  active_neorg = false,
  active_org = false,
  active_autopairs = true,
  active_lsp = true,
  active_refactor = true,
  active_dap = false,
  active_tint = false,
  autocmds = {
    custom_groups = {
      { "BufWinEnter", "*.go", "setlocal ts=4 sw=4" },
      { "BufWinEnter", "*.c", "setlocal ts=4 sw=4" },
      { "BufWinEnter", "*.cpp", "setlocal ts=4 sw=4" },
      { "BufWinEnter", "*.h", "setlocal ts=4 sw=4" },
      { "BufWinEnter", "*.php", "setlocal ts=4 sw=4" },
    },
  },
}
